app:
  jwt:
    secret: ENC(hzyJMZWhIyoKIOW28ATJSil5YgR0H8y5zPR1ixFK+noTi7OSXrclkHVE1xe9SzCrdrqrJpwlRsxf5IoYhg3Hjvu5f4dadiOKDMvknSVgmB1CQxPIRkEgrH5xh8jNjuuLen40TZCoU/3taRfDKzWNDg==)
    iss: the-elite-chat-rooms
    aud: chat-service
  google-api:
    host: www.googleapis.com
    auth:
      host: oauth2.googleapis.com
      clientId: ENC(jqTmTVlocjWR6tsqvtasNpGdVC4RYUD4j8fa/C2VIPYRZfan+dpKCWFfeaEc9r1tYaNPujI/L+jR2jYIMXhO2DfFRNzjX3D44Rp3lSrcelZjIc5qqKHdbmT2LZoXgisrAqox6XHOmMoz1KAIHW2qbg==)
      clientSecret: ENC(8+dzMZ+iFwiXgD0SAo3fLUQ85GZUYNx/xP4HkaerI3AMVbdL6xKG4WxnZHz5HxFABx+8lCn21rnQ22eEtSt55Bf9W0p+sJSNvi0XE3BCNts=)
      redirect_uri: http://localhost:3000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chat_rooms
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create-drop #update
    show-sql: true
    properties:
      format_sql: true

  redis:
    host: localhost
    port: 6379

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%X{correlationId}] %logger{36} - %msg%n"
