server:
  port: 8080

spring:
  kafka:
    bootstrap-servers: localhost:9092,localhost:9094,localhost:9096
    producer:
      acks: all

app:
  jwtSecret: 61fa7f0ba87e49a5419f0c6a686d9f6191c649bb48d917b77e356298663a1d64
  cors:
    allowed-origins: http://localhost:3000
  kafka:
    schema-registry-url: localhost:8081

