server:
  port: 0

spring:
  kafka:
    bootstrap-servers: localhost:9092,localhost:9094,localhost:9096
    producer:
      acks: all

app:
  cors:
    allowed-origins: localhost:3000
  kafka:
    schema-registry-url: localhost:8081