spring:
  kafka:
    bootstrap-servers: localhost:9092,localhost:9094,localhost:9096

  datasource:
    url: jdbc:mysql://localhost:3306/chat_rooms
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true
    properties:
      format_sql: true

app:
  cors:
    allowed-origins: http://localhost:3000
#  kafka:
#    schema-registry-url: localhost:8081
  auth-server:
    request:
      host: localhost
      port: 8081

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%X{correlationId}] %logger{36} - %msg%n"

